apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  annotations:
    kubernetes.io/change-cause: "image updated to 1.27.3"
spec:
  replicas: 3 # 복제본 항상 3개 유지
  selector:
    matchLabels: # 이 디플로이먼트가 관리할 라벨 찾기
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx # 파드 라벨 지정
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.3
        ports:
        - containerPort: 80
